app-id: com.intelligent_username.tmd
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: tmd
finish-args:
  - --filesystem=host
  - --share=network

modules:
  - name: tmd
    buildsystem: simple
    build-commands:
      - install -Dm755 tmd-linux-x64 /app/bin/tmd || install -Dm755 tmd-linux-arm64 /app/bin/tmd
      - install -Dm644 com.intelligent_username.tmd.metainfo.xml /app/share/metainfo/com.intelligent_username.tmd.metainfo.xml
    sources:
      - type: file
        url: https://github.com/intelligent-username/tokens.md/releases/download/v0.0.18/tmd-linux-x64
        sha256: 11b4ad968671c76e7aa4fb5cc5bc6b740e77fea86c98417a0a11a57e855718e1
        dest-filename: tmd-linux-x64
        only-arches:
          - x86_64
      - type: file
        url: https://github.com/intelligent-username/tokens.md/releases/download/v0.0.18/tmd-linux-arm64
        sha256: d135d720840cff69a652c544c26d2dd45acfbe9f09577da6005433be6d1f6b70
        dest-filename: tmd-linux-arm64
        only-arches:
          - aarch64
      - type: file
        path: com.intelligent_username.tmd.metainfo.xml
