name: Build Binaries

on:
  workflow_call:

jobs:
  build-linux-x64:
    uses: ./.github/workflows/builders/build-linux-x64.yml

  build-linux-arm64:
    uses: ./.github/workflows/builders/build-linux-arm64.yml

  build-macos-arm64:
    uses: ./.github/workflows/builders/build-macos-arm64.yml

  build-macos-x64:
    uses: ./.github/workflows/builders/build-macos-x64.yml

  build-windows-x64:
    uses: ./.github/workflows/builders/build-windows-x64.yml

  build-windows-arm64:
    uses: ./.github/workflows/builders/build-windows-arm64.yml
